version: '3'
services:
  nginx:
    image: nginx
    depends_on: 
      - web-application
    volumes:
      - ./Web-Application/src/presentation-layer-api/SPA/:/usr/share/nginx/html/
    ports:
      - 8000:80
  web-application:
    build: "./web-application"
    ports:
      - 80:80
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - redis
      - database
    environment:
      - JWT_KEY=${JWT_KEY}
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  redis:
      image: redis
      ports:
        - 6379:6379
      